
- name: Install git
  become: true
  ansible.builtin.apt:
    pkg: git

- name: Configure git
  become: false
  ansible.builtin.shell: |
    git config --global user.name "Stanislav Zaleski"
    git config --global user.email "sigmaray@gmail.com"
