---
- name: Install etckeeper
  become: true
  ansible.builtin.apt:
    name: etckeeper
    state: present
    install_recommends: false

- name: Initialize etckeeper repository.
  ansible.builtin.shell: etckeeper init
  args:
    chdir: /etc/
    creates: /etc/.etckeeper
  tags:
    - skip_ansible_lint
