---
- name: Install etckeeper.
  ansible.builtin.apt:
    name: etckeeper
    state: present
    install_recommends: false
    update_cache: true

- name: Initialize etckeeper repository.
  ansible.builtin.shell: etckeeper init
  args:
    chdir: /etc/
    creates: /etc/.etckeeper
