---
# https://code.visualstudio.com/docs/setup/linux

# https://github.com/gantsign/ansible-role-visual-studio-code/blob/master/tasks/install-apt.yml

# - name: Install dependencies (apt)
#   become: true
#   ansible.builtin.apt:
#     name:
#       - ca-certificates
#       - apt-transport-https
#       - gconf2
#       - libasound2
#       - libgtk2.0-0
#       - libxss1
#       - libxcb-dri3-0
#       - libdrm2
#       - libgbm1
#       - libxshmfence1
#     state: present

- name: Install deps
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - wget
      - gpg 
      - ca-certificates   
      - apt-transport-https

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: Install key (apt)
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: yes

- name: Install VS Code repo (apt)
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Install VS Code (apt)
  become: true
  ansible.builtin.apt:
    name: code
    state: present
###############3

# ---

# - name: Add Apt signing key
#   shell: >
# - name: Add repository into sources list
#   ansible.builtin.apt_repository:
#     repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
#     state: present
#     filename: google-chrome
# - name: Install google-chrome-stable
#   apt:
#     pkg:
#       - google-chrome-stable
#       - google-chrome-beta


# sudo apt-get install wget gpg
# wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
# sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
# sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
# rm -f packages.microsoft.gpg
