---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # image: quay.io/centos/centos:stream8
    image: nmusatti/ubuntu2204-pys
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
